name: append
on:
    push:
        branches: main 
    
jobs:
    deploy_to_live:
            name: Deploy prod hosting
            runs-on: ubuntu-latest
            strategy: 
              matrix: 
                node: [12]
            steps:
                - uses: actions/checkout@v2
                - name: Use Node.js ${{ matrix.node }}
                - uses: actions/setup-node@v1
                  with:
                     node-version: ${{ matrix.node }}
                - name: step3
                  run: npm install
                - name: step4
                  run: npm run build --if-present
                - name: step5
                  run: node learnfile.js
